# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzBmMzM2NTk0YTEzNGQ3OTkwNDI1YTdkNjEyZDgxZjU2ZWZiMjVmNDM3Y2M3YzQ4ODM1MjFmMmNjZTU5YjM1MTE4NzhmM2VjZjQwYmE3ZDE4N2FiOWM0NzViOTM1YjdlNzhkNDU5OWNhYjMyNGRjNDRhM2FkZGZkMzA4N2EzNTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
